### ISSUE TITLE
Suggest license

### ISSUE THREAD

**Issue by xstp** [pry0cc/tew#6]
Thanks for this package! It's really cool. But I saw that under license, you do not have any license. Legally this means no one can use or modify it. Can you add a license?

For more on this you can read [this](https://choosealicense.com/no-permission/)  page.

**Comment by pry0cc** [comment]
Thank you, i need to decide on a license… Any ideas on the pros and cons?

**Comment by pry0cc** [comment]
Gonna go MIT.
